---
version: 2.1

orbs:
  orb: circleci/orb-tools@9.1

workflows:
  lint-pack-validate-publish-dev:
    jobs:
      - orb/lint
      - orb/pack
      - orb/publish-dev:
          orb-name: jorjazo/kubernetes
          context: personal
          requires:
            - orb/pack
            - orb/lint
      - approve-promote:
          type: approval
          requires:
            - orb/publish-dev
      - orb/dev-promote-prod-from-commit-subject:
          orb-name: jorjazo/kubernetes
          context: personal
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: b2:a6:74:c0:d2:4e:20:93:c6:98:f2:f9:66:6b:d0:9d
          requires:
            - approve-promote
          filters:
            branches:
              only: master
