---
version: 2.1

orbs:
  orb: circleci/orb-tools@9.1

workflows:
  lint-pack-validate-publish-dev:
    jobs:
      - orb/lint
      - orb/pack
      - orb/publish-dev:
          orb-name: jorjazo/boot
          context: personal
          requires:
            - orb/pack
            - orb/lint
      - approve-promote:
          type: approval
          requires:
            - orb/publish-dev
      - orb/dev-promote-prod-from-commit-subject:
          orb-name: jorjazo/boot
          context: personal
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: c9:f4:40:d8:eb:51:6b:bf:71:37:4b:89:22:22:c7:3d
          requires:
            - approve-promote
          filters:
            branches:
              only: master
